[package]
name = "dungeon_delivery"
version = "0.1.0"
edition = "2021"

[dependencies]
lore_render = { git = "https://github.com/sepiatonal/lore.git", rev = "524f076b699dbee2a9fabebfff7da3d5fdd3a233" }
#lore_render = { path = "../lore_project/lore_render" }