[package]
name = "dungeon_delivery"
version = "0.1.0"
edition = "2021"

[dependencies]
lore_render = { git = "https://github.com/sepiatonal/lore.git", rev = "b06007c82df63c8c9dbddf5c05c0fa83efd4e1ad" }
#lore_render = { path = "../lore_project/lore_render" }